### ISSUE TITLE
Do we need the data-prop-location?

### ISSUE THREAD

**Issue by skartknet** [prjseal/QuickBlocks#3]
### Feature summary

Hey Paul, again thank you for this package. I think it's a great idea and I'm very excited about it. I think it can be super useful. Where I work we use also headless CMSs and this tool could be great for frontend developers.

I'd like to start making some comments here and maybe some suggestions. But don't get overwhelmed! I know it's a very early version and we do this mostly on own our time.

First thing I'd like to ask you is about the `data-prop-location` attribute. Do we really need that? I mean, if we are inside a row, define by `data-row-name`, aren't we just creating all the properties in here for that row implicitely?

**Comment by prjseal** [comment]
Hi Mario
Yes the location is an extra that I don’t want, I’ve not worked out how to refactor it to not need it yet but I do agree it needs fixing
